# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
# Stacks detected: cicd:empty:
version: 2.1

jobs:
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      # Replace this with a real test runner invocation
      - run: echo 'My favorite colour is' $colour
      - run:
          name: Run tests
          command: echo 'replace me with real tests!'
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: circleci tests run --help
      # Replace this with steps to build a package, or executable
      - run: echo 'My favorite colour is' $colour
      - run:
          name: Build an artifact
          command: touch example.txt
      - store_artifacts:
          path: example.txt
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      # Replace this with steps to deploy to users
      - run: echo 'My favorite colour is' $colour
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'
      - run:
          name: found empty repo
          command: ':'
workflows:
  example:
    jobs:
      - test:
          context: &job-context test
      - build:
          requires:
            - test
          context: *job-context
      - deploy:
          requires:
            - test
          context: *job-context
